tasks:
  - name: Setup
    before: |
      sudo apt update -y
      sudo apt-get install git -y
      sudo apt-get install gcc -y
      sudo apt-get install build-essential -y
      sudo apt-get install libcurl4-gnutls-dev -y
      sudo apt-get install libfreeimage-dev -y
      sudo apt-get install libssl-dev -y
      sudo apt-get install libpq-dev -y
      sudo apt-get install libmysqlclient-dev -y
      chmod +x /workspace/core/bin/linux/hbmshell
      sudo ln -s /workspace/core/bin/linux/hbmshell /usr/local/bin/hbmshell
      chmod +x /workspace/core/harbour
vscode:
  extensions:
    - aperricone.harbour
    - formulahendry.code-runner