//-dINCLUI='foo'
//-dVERSION=12
//-dHOJE=DATE()
//-dDATE_VERSION=0d20020608
PROCEDURE MAIN

    ? "VALUES DEFINED IN COMPILATION TIME"
    ? INCLUI
    ? HOJE
    ? VERSION + 100
    ? DATE_VERSION	 

RETURN
